### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by victornpb** [fabiomcosta/micro-selector#3]
What is the minimum browser support for this?

**Comment by fabiomcosta** [comment]
@victornpb this library should work pretty much in any browser from IE6 up.

**Comment by victornpb** [comment]
would be nice to have this info on the readme

**Comment by fabiomcosta** [comment]
@victornpb I'll add that now, thank you for the suggestion!

**Comment by fabiomcosta** [comment]
Just added it @victornpb
